name: Test Code

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

      # Steps taken from https://github.com/actions/cache/blob/master/examples.md#rust---cargo
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup toolchain
      run: ./scripts/init.sh

    # Enable this for clippy linting.
    # - name: Check and Lint Code
    #   run: cargo +nightly-2020-05-07 clippy -- -D warnings

    - name: Check Code
      run: cargo check --all

    - name: Test Code
      run: cargo test --all

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup toolchain
      run: ./scripts/init.sh

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Run cargo fmt
      run: cargo fmt --all -- --check